#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# sg-playwright-vnc — install the proxy CA into the browsers' trust stores
#
# WHY: SG_PLAYWRIGHT__IGNORE_HTTPS_ERRORS makes pages LOAD through mitmproxy, but
# it suppresses the error at the network layer only — Chromium still paints the
# omnibox "Not secure" because the re-signing CA isn't trusted. Installing the CA
# gives a real padlock in the interactive fleet browsers.
#
# Two stores, because Linux browsers don't agree on one:
#   • system store (/usr/local/share/ca-certificates + update-ca-certificates) —
#     used by curl/python/openssl in the container, and by Chromium builds that
#     defer to the system roots.
#   • NSS user DB ($HOME/.pki/nssdb) — the canonical place Chromium on Linux
#     reads user-added roots from.
#
# The CA is generated by mitmproxy on ITS first start, so the mounted file may not
# exist yet when this container boots — wait (bounded), then install. Always
# exits 0: an untrusted CA is cosmetic (ignore-https-errors still loads pages), so
# this must never block the desktop from coming up.
#
# Firefox caveat: Playwright creates a FRESH profile per launch, and Firefox reads
# roots from that profile's own NSS DB — so a Firefox fleet browser may still show
# the warning. Chromium (the default engine) is covered.
# ═══════════════════════════════════════════════════════════════════════════════
set -u

CA_FILE="${SG_PLAYWRIGHT__PROXY_CA_FILE:-/certs/mitmproxy-ca-cert.pem}"
MARKER="/tmp/ca-trust.done"
NSSDB="${HOME:-/root}/.pki/nssdb"

finish() { : > "$MARKER"; exit 0; }                                                  # autostart-browser waits on this marker

[ -z "$CA_FILE" ] && finish

for i in $(seq 1 30); do                                                             # mitmproxy self-generates its CA on first start
    [ -s "$CA_FILE" ] && break
    sleep 2
done

if [ ! -s "$CA_FILE" ]; then
    echo "[ca-trust] no CA at $CA_FILE after 60s — browsers will show 'Not secure' (pages still load via ignore-https-errors)"
    finish
fi

echo "[ca-trust] installing $CA_FILE into the system store"
cp "$CA_FILE" /usr/local/share/ca-certificates/mitmproxy-ca.crt 2>/dev/null \
  && update-ca-certificates >/dev/null 2>&1 \
  || echo "[ca-trust] WARNING: system store install failed"

echo "[ca-trust] installing into the Chromium NSS DB ($NSSDB)"
mkdir -p "$NSSDB"
certutil -d sql:"$NSSDB" -N --empty-password >/dev/null 2>&1 || true                 # create the DB when absent (no-op if it exists)
certutil -d sql:"$NSSDB" -A -t "C,," -n "mitmproxy CA" -i "$CA_FILE" >/dev/null 2>&1 \
  && echo "[ca-trust] done — Chromium will show a padlock for proxied sites" \
  || echo "[ca-trust] WARNING: NSS install failed — omnibox will show 'Not secure'"

finish
