# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — vault-app: Vault_App__Reverse_Proxy__Override
# Runtime-injection of a same-origin reverse proxy into the sg-send-vault
# container WITHOUT rebuilding the diniscruz/sg-send-vault image.
#
# We control the launch (compose + user-data), so we bind-mount a small package
# at /app/sg_overrides and override the container command to our own entrypoint.
# Our entrypoint wraps the stock boot — create_app() (their app, untouched) →
# mount the reverse-proxy routes → their Fast_API__TLS__Launcher.serve(). Zero
# edits to the image; the only coupling is two import names (create_app + the
# TLS launcher), which fail loud at boot if the image ever renames them.
#
# Three files are written to the host overrides dir and bind-mounted in:
#   __init__.py              — makes sg_overrides a package
#   Fast_API__Reverse_Proxy.py — the SHIPPED source of the shared proxy class
#                                (read from sg_compute.fast_api.reverse_proxy)
#   serve_with_proxy.py      — our entrypoint (Send-specific imports)
#
# This is the "runtime injection" pattern (tech spec Option A2); the Playwright
# proxy is its first case study. The durable fix is the upstream PR to
# SGraph-AI__App__Send — see the handover brief.
# ═══════════════════════════════════════════════════════════════════════════════

import importlib.util
from pathlib                            import Path

from osbot_utils.type_safe.Type_Safe    import Type_Safe

OVERRIDES_DIR        = '/opt/vault-app/overrides'
REVERSE_PROXY_MODULE = 'sg_compute.fast_api.reverse_proxy.Fast_API__Reverse_Proxy'

# Our entrypoint override. Wraps the stock sg-send-vault boot: same create_app()
# and the same TLS launcher, with one line injected between them. Replicates the
# image's own serve.py (http_port=8080) so TLS-on/off behaviour is identical.
SERVE_WITH_PROXY = '''\
# Generated by Vault_App__Reverse_Proxy__Override — entrypoint override for the
# sg-send-vault container. create_app() (unchanged) -> mount reverse proxy ->
# the image's own TLS launcher. Fails loud if the image renames either symbol.
from sgraph_ai_app_send__docker.app                     import create_app
from sgraph_ai_app_send__docker.Fast_API__TLS__Launcher import Fast_API__TLS__Launcher
from sg_overrides.Fast_API__Reverse_Proxy               import Fast_API__Reverse_Proxy

APP__HTTP_PORT = 8080                                       # plain-HTTP port when TLS is off (matches the image serve.py)


def main():
    app    = create_app()                                   # the stock vault app, untouched
    routes = Fast_API__Reverse_Proxy().mount(app)           # inject /pw/* from FAST_API__REVERSE_PROXY__ROUTES
    print(f"[sg_overrides] reverse-proxy routes mounted: {routes}", flush=True)
    Fast_API__TLS__Launcher().serve(app, http_port=APP__HTTP_PORT)


if __name__ == "__main__":
    main()
'''


class Vault_App__Reverse_Proxy__Override(Type_Safe):

    def reverse_proxy_source(self) -> str:                                         # SHIPPED source of the shared proxy class — located without importing it (no fastapi at CLI time)
        spec = importlib.util.find_spec(REVERSE_PROXY_MODULE)
        if spec is None or not spec.origin:
            raise FileNotFoundError(f'cannot locate {REVERSE_PROXY_MODULE} to ship into the container')
        return Path(spec.origin).read_text()

    def render_write_block(self, overrides_dir: str = OVERRIDES_DIR) -> str:       # bash that writes the 3 override files to the host (before `compose up`)
        files = (('__init__.py'              , ''                          ),
                 ('Fast_API__Reverse_Proxy.py', self.reverse_proxy_source()),
                 ('serve_with_proxy.py'       , SERVE_WITH_PROXY            ))
        lines = ['\n# ── sg-send-vault reverse-proxy override (runtime injection) ─────────────────',
                 f'echo "[vault-app] writing reverse-proxy overrides to {overrides_dir}"',
                 f'mkdir -p {overrides_dir}']
        for name, content in files:
            lines.append(self._heredoc(f'{overrides_dir}/{name}', content, delim='SG_OVERRIDE_EOF'))
        lines.append('echo "[vault-app] reverse-proxy overrides written"\n')
        return '\n'.join(lines)

    def _heredoc(self, path: str, content: str, delim: str) -> str:                # quoted-delim heredoc; plain concatenation so the Python payload's { } are never reinterpreted
        return 'cat > ' + path + " <<'" + delim + "'\n" + content + '\n' + delim
