# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — vault-app: Vault_App__Compose__Template
# Renders the docker-compose.yml the EC2 host writes to /opt/vault-app/.
#
# Two shapes, selected by `with_playwright`:
#   just-vault     (default)  — host-plane + sg-send-vault            (2 containers)
#   with-playwright           — + sg-playwright + agent-mitmproxy     (4 containers)
#
# Only sg-send-vault publishes a host port (8080). Every other service stays on
# the internal vault-net bridge — reach them with an SSM port-forward.
#
# All ${...} values are resolved by the compose engine from /opt/vault-app/.env
# at `up` time — never interpolated here.
# ═══════════════════════════════════════════════════════════════════════════════

from osbot_utils.type_safe.Type_Safe import Type_Safe

SG_SEND_VAULT_IMAGE = 'diniscruz/sg-send-vault:latest'
SG_PLAYWRIGHT_IMAGE = 'diniscruz/sg-playwright:latest'

_HEADER = '''\
# Generated by Vault_App__Compose__Template — do not edit by hand.
services:
'''

_HOST_PLANE = '''
  host-plane:
    image: {ecr_registry}/sgraph_ai_service_playwright_host:{image_tag}
    ports:
      - "127.0.0.1:19009:8000"   # localhost-only on the EC2 host; reachable via SSM port-forward only
    volumes:
      - {docker_socket}:/var/run/docker.sock
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}
    networks:
      - vault-net
    restart: unless-stopped
'''

_SG_SEND_VAULT = '''
  sg-send-vault:
    image: {sg_send_vault_image}
    ports:
      - "8080:8080"
    volumes:
      - ${{VAULT_DATA_PATH:-/opt/vault-app/data}}:/data
    environment:
      SGRAPH_SEND__ACCESS_TOKEN:     ${{SGRAPH_SEND__ACCESS_TOKEN}}
      SEND__STORAGE_MODE:            ${{SEND__STORAGE_MODE:-disk}}
      SG_VAULT_APP__SEED_VAULT_KEYS: ${{SG_VAULT_APP__SEED_VAULT_KEYS:-}}
    networks:
      - vault-net
    restart: unless-stopped
'''

# TLS variant — sg-send-vault terminates its own HTTPS on :443 via the §8.2
# FAST_API__TLS__* contract, reading the cert the one-shot cert-init sidecar
# wrote to the shared volume. Gated behind cert-init via depends_on, so a failed
# issuance means the vault never starts (fail-loud, not silent plain-HTTP).
# With TLS on, the app binds :443 only — :8080 is no longer published.
_SG_SEND_VAULT_TLS = '''
  sg-send-vault:
    image: {sg_send_vault_image}
    ports:
      - "443:443"
    volumes:
      - ${{VAULT_DATA_PATH:-/opt/vault-app/data}}:/data
      - certs:/certs:ro
    environment:
      SGRAPH_SEND__ACCESS_TOKEN:     ${{SGRAPH_SEND__ACCESS_TOKEN}}
      SEND__STORAGE_MODE:            ${{SEND__STORAGE_MODE:-disk}}
      SG_VAULT_APP__SEED_VAULT_KEYS: ${{SG_VAULT_APP__SEED_VAULT_KEYS:-}}
      FAST_API__TLS__ENABLED:        "true"
      FAST_API__TLS__CERT_FILE:      /certs/cert.pem
      FAST_API__TLS__KEY_FILE:       /certs/key.pem
      FAST_API__TLS__PORT:           "443"
    networks:
      - vault-net
    depends_on:
      cert-init:
        condition: service_completed_successfully
    restart: unless-stopped
'''

_SG_PLAYWRIGHT = '''
  sg-playwright:
    image: {sg_playwright_image}
    ports:
      - "80:8000"                # standard port (Claude/sandbox egress proxies only allow :80/:443); see PLAYWRIGHT_EXTERNAL_PORT
    environment:
      FAST_API__AUTH__API_KEY__NAME:      ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE:     ${{FAST_API__AUTH__API_KEY__VALUE}}
      SG_PLAYWRIGHT__DEPLOYMENT_TARGET:   container
      SG_PLAYWRIGHT__DEFAULT_PROXY_URL:   http://agent-mitmproxy:8080
      SG_PLAYWRIGHT__IGNORE_HTTPS_ERRORS: 'true'
    networks:
      - vault-net
    depends_on:
      agent-mitmproxy:
        condition: service_started
      cert-init:                  # cert-init also binds :80 (http-01 challenge) — wait for it to exit before grabbing the port
        condition: service_completed_successfully
        required: false           # ignored when cert-init isn't in the stack (--no-with-tls-check)
    restart: unless-stopped
'''

_AGENT_MITMPROXY = '''
  agent-mitmproxy:
    image: {ecr_registry}/agent_mitmproxy:{image_tag}
    ports:
      - "127.0.0.1:19081:8000"   # admin FastAPI (incl. Routes__Web /web/* → mitmweb:8081); SSM-only
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}
    networks:
      - vault-net
    restart: unless-stopped
'''

# One-shot cert sidecar — runs the host image (it already carries sg_compute),
# writes /certs/{cert,key}.pem, and exits 0. self-signed mode is offline;
# letsencrypt-ip mode runs an http-01 ACME challenge on :80 (hence the published
# port — harmless in self-signed mode, nothing listens after the sidecar exits).
# See the v0.2.6 TLS architecture doc §8.1.
_CERT_INIT = '''
  cert-init:
    image: {ecr_registry}/sgraph_ai_service_playwright_host:{image_tag}
    command: ["python", "-m", "sg_compute.platforms.tls.cert_init"]
    environment:
      SG__CERT_INIT__MODE:         ${{SG__CERT_INIT__MODE:-self-signed}}
      SG__CERT_INIT__COMMON_NAME:  ${{SG__CERT_INIT__COMMON_NAME:-}}
      SG__CERT_INIT__ACME_PROD:    ${{SG__CERT_INIT__ACME_PROD:-false}}
      SG__CERT_INIT__ACME_EMAIL:   ${{SG__CERT_INIT__ACME_EMAIL:-}}
      SG__CERT_INIT__TLS_HOSTNAME: ${{SG__CERT_INIT__TLS_HOSTNAME:-}}   # FQDN for letsencrypt-hostname mode; ignored for the other modes
      FAST_API__TLS__CERT_FILE:   /certs/cert.pem
      FAST_API__TLS__KEY_FILE:    /certs/key.pem
    ports:
      - "80:80"
    volumes:
      - certs:/certs
    networks:
      - vault-net
    restart: "no"
'''

_NETWORKS = '''
networks:
  vault-net:
    driver: bridge
'''

_VOLUMES = '''
volumes:
  certs:
'''


class Vault_App__Compose__Template(Type_Safe):

    def render(self, ecr_registry        : str  ,
                     with_playwright     : bool = False                       ,
                     image_tag           : str  = 'latest'                    ,
                     sg_send_vault_image : str  = SG_SEND_VAULT_IMAGE          ,
                     sg_playwright_image : str  = SG_PLAYWRIGHT_IMAGE          ,
                     docker_socket       : str  = '/var/run/docker.sock'      ,
                     with_tls_check      : bool = False                        ) -> str:
        vault_block = (_SG_SEND_VAULT_TLS if with_tls_check else _SG_SEND_VAULT)
        parts = [
            _HEADER                                                                          ,
            _HOST_PLANE.format(ecr_registry  = ecr_registry  ,
                               image_tag     = image_tag     ,
                               docker_socket = docker_socket),
            vault_block.format(sg_send_vault_image=sg_send_vault_image)                       ,
        ]
        if with_playwright:
            parts.append(_SG_PLAYWRIGHT.format(sg_playwright_image=sg_playwright_image))
            parts.append(_AGENT_MITMPROXY.format(ecr_registry=ecr_registry, image_tag=image_tag))
        if with_tls_check:
            parts.append(_CERT_INIT.format(ecr_registry=ecr_registry, image_tag=image_tag))
        parts.append(_NETWORKS)
        if with_tls_check:
            parts.append(_VOLUMES)
        return ''.join(parts)
