# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — vault-app: Vault_App__Compose__Template
# Renders the docker-compose.yml the EC2 host writes to /opt/vault-app/.
#
# Two shapes, selected by `with_playwright`:
#   just-vault     (default)  — host-plane + sg-send-vault            (2 containers)
#   with-playwright           — + sg-playwright + agent-mitmproxy     (4 containers)
#
# Only sg-send-vault publishes a host port (8080). Every other service stays on
# the internal vault-net bridge — reach them with an SSM port-forward.
#
# All ${...} values are resolved by the compose engine from /opt/vault-app/.env
# at `up` time — never interpolated here.
# ═══════════════════════════════════════════════════════════════════════════════

from osbot_utils.type_safe.Type_Safe import Type_Safe

SG_SEND_VAULT_IMAGE = 'diniscruz/sg-send-vault:latest'

_HEADER = '''\
# Generated by Vault_App__Compose__Template — do not edit by hand.
services:
'''

_HOST_PLANE = '''
  host-plane:
    image: {ecr_registry}/sgraph_ai_service_playwright_host:{image_tag}
    volumes:
      - {docker_socket}:/var/run/docker.sock
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}
    networks:
      - vault-net
    restart: unless-stopped
'''

_SG_SEND_VAULT = '''
  sg-send-vault:
    image: {sg_send_vault_image}
    ports:
      - "8080:8080"
    volumes:
      - ${{VAULT_DATA_PATH:-/opt/vault-app/data}}:/data
    environment:
      SGRAPH_SEND__ACCESS_TOKEN:     ${{SGRAPH_SEND__ACCESS_TOKEN}}
      SEND__STORAGE_MODE:            ${{SEND__STORAGE_MODE:-disk}}
      SG_VAULT_APP__SEED_VAULT_KEYS: ${{SG_VAULT_APP__SEED_VAULT_KEYS:-}}
    networks:
      - vault-net
    restart: unless-stopped
'''

_SG_PLAYWRIGHT = '''
  sg-playwright:
    image: {ecr_registry}/sgraph_ai_service_playwright:{image_tag}
    environment:
      FAST_API__AUTH__API_KEY__NAME:      ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE:     ${{FAST_API__AUTH__API_KEY__VALUE}}
      SG_PLAYWRIGHT__DEPLOYMENT_TARGET:   container
      SG_PLAYWRIGHT__DEFAULT_PROXY_URL:   http://agent-mitmproxy:8080
      SG_PLAYWRIGHT__IGNORE_HTTPS_ERRORS: 'true'
    networks:
      - vault-net
    depends_on:
      - agent-mitmproxy
    restart: unless-stopped
'''

_AGENT_MITMPROXY = '''
  agent-mitmproxy:
    image: {ecr_registry}/agent_mitmproxy:{image_tag}
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}
    networks:
      - vault-net
    restart: unless-stopped
'''

# TLS PoC — a one-shot cert sidecar seeds /certs, then Fast_API__TLS serves the
# secure-context-check page over HTTPS on :443. cert-init runs to completion
# first; tls-check is gated behind it via depends_on. Both run the host image
# (it already carries sg_compute) — see the v0.2.6 TLS PoC architecture doc.
_CERT_INIT = '''
  cert-init:
    image: {ecr_registry}/sgraph_ai_service_playwright_host:{image_tag}
    command: ["python", "-m", "sg_compute.platforms.tls.cert_init"]
    environment:
      SG__CERT_INIT__COMMON_NAME: ${{SG__CERT_INIT__COMMON_NAME:-}}
      FAST_API__TLS__CERT_FILE:   /certs/cert.pem
      FAST_API__TLS__KEY_FILE:    /certs/key.pem
    volumes:
      - certs:/certs
    networks:
      - vault-net
    restart: "no"
'''

_TLS_CHECK = '''
  tls-check:
    image: {ecr_registry}/sgraph_ai_service_playwright_host:{image_tag}
    command: ["python", "-m", "sg_compute.fast_api.tls.lambda_handler"]
    environment:
      FAST_API__TLS__ENABLED:   "true"
      FAST_API__TLS__CERT_FILE: /certs/cert.pem
      FAST_API__TLS__KEY_FILE:  /certs/key.pem
      FAST_API__TLS__PORT:      "443"
    ports:
      - "443:443"
    volumes:
      - certs:/certs:ro
    networks:
      - vault-net
    depends_on:
      cert-init:
        condition: service_completed_successfully
    restart: unless-stopped
'''

_NETWORKS = '''
networks:
  vault-net:
    driver: bridge
'''

_VOLUMES = '''
volumes:
  certs:
'''


class Vault_App__Compose__Template(Type_Safe):

    def render(self, ecr_registry        : str  ,
                     with_playwright     : bool = False                       ,
                     image_tag           : str  = 'latest'                    ,
                     sg_send_vault_image : str  = SG_SEND_VAULT_IMAGE          ,
                     docker_socket       : str  = '/var/run/docker.sock'      ,
                     with_tls_check      : bool = False                        ) -> str:
        parts = [
            _HEADER                                                                          ,
            _HOST_PLANE.format(ecr_registry=ecr_registry, image_tag=image_tag,
                               docker_socket=docker_socket)                                  ,
            _SG_SEND_VAULT.format(sg_send_vault_image=sg_send_vault_image)                    ,
        ]
        if with_playwright:
            parts.append(_SG_PLAYWRIGHT.format(ecr_registry=ecr_registry, image_tag=image_tag))
            parts.append(_AGENT_MITMPROXY.format(ecr_registry=ecr_registry, image_tag=image_tag))
        if with_tls_check:
            parts.append(_CERT_INIT.format(ecr_registry=ecr_registry, image_tag=image_tag))
            parts.append(_TLS_CHECK.format(ecr_registry=ecr_registry, image_tag=image_tag))
        parts.append(_NETWORKS)
        if with_tls_check:
            parts.append(_VOLUMES)
        return ''.join(parts)
