# ═══════════════════════════════════════════════════════════════════════════════
# SP CLI — Routes__Ec2__Playwright
# Action-mapped HTTP surface for the Playwright EC2 stack (Playwright service +
# agent_mitmproxy sidecar + headless Chromium). The CLI shape `sp <command>
# [<name>]` is mirrored 1:1 in the URL: /ec2/playwright/{command}/{name?}.
#
# Endpoints
# ─────────
#   GET    /ec2/playwright/list                -> Schema__Ec2__Instance__List
#   GET    /ec2/playwright/info/{name}         -> Schema__Ec2__Instance__Info  (404 on miss)
#   POST   /ec2/playwright/create              -> Schema__Ec2__Create__Response (deploy_name from body or auto-generated)
#   POST   /ec2/playwright/create/{name}       -> Schema__Ec2__Create__Response (deploy_name pinned to {name}, overriding body)
#   DELETE /ec2/playwright/delete/{name}       -> Schema__Ec2__Delete__Response (404 on miss)
#   DELETE /ec2/playwright/delete-all          -> Schema__Ec2__Delete__Response (terminated_instance_ids may be empty if no instances)
#
# `name` can be either the deploy-name (e.g. `grand-wien`) or the instance-id
# (e.g. `i-03bdcec5e71f85688`) — Ec2__Service.resolve_target accepts both.
#
# Routes carry zero logic — they delegate to Ec2__Service and serialise the
# Type_Safe response. /ec2/mitmproxy/* and any future EC2 stack types live in
# their own Routes__Ec2__* sibling so each resource has one dedicated file.
# ═══════════════════════════════════════════════════════════════════════════════

from fastapi                                                                        import HTTPException

from osbot_fast_api.api.routes.Fast_API__Routes                                     import Fast_API__Routes

from sgraph_ai_service_playwright__cli.ec2.schemas.Schema__Ec2__Create__Request     import Schema__Ec2__Create__Request
from sgraph_ai_service_playwright__cli.ec2.service.Ec2__Service                     import Ec2__Service


TAG__ROUTES_EC2_PLAYWRIGHT = 'ec2/playwright'                                       # Becomes the URL prefix; OpenAPI groups all five endpoints together


class Routes__Ec2__Playwright(Fast_API__Routes):
    tag     : str          = TAG__ROUTES_EC2_PLAYWRIGHT
    service : Ec2__Service                                                          # Injected by Fast_API__SP__CLI.setup_routes()

    def list_instances(self) -> dict:                                               # GET /ec2/playwright/list
        return self.service.list_instances().json()
    list_instances.__route_path__ = '/list'

    def info(self, name: str) -> dict:                                              # GET /ec2/playwright/info/{name}
        result = self.service.get_instance_info(name)
        if result is None:
            raise HTTPException(status_code=404, detail=f'no instance matched {name!r}')
        return result.json()
    info.__route_path__ = '/info/{name}'

    def create(self, body: Schema__Ec2__Create__Request) -> dict:                   # POST /ec2/playwright/create — deploy_name from body or auto-generated by provision_ec2
        return self.service.create(body).json()
    create.__route_path__ = '/create'

    def create_named(self, name: str, body: Schema__Ec2__Create__Request) -> dict:  # POST /ec2/playwright/create/{name} — path name wins over body.deploy_name
        body.deploy_name = name                                                     # Safe_Str__Deploy_Name coerces from a plain str on assignment
        return self.service.create(body).json()
    create_named.__route_path__ = '/create/{name}'

    def delete(self, name: str) -> dict:                                            # DELETE /ec2/playwright/delete/{name}
        response = self.service.delete_instance(name)
        if not response.terminated_instance_ids:
            raise HTTPException(status_code=404, detail=f'no instance matched {name!r}')
        return response.json()
    delete.__route_path__ = '/delete/{name}'

    def delete_all(self) -> dict:                                                   # DELETE /ec2/playwright/delete-all — terminated_instance_ids may be empty
        return self.service.delete_all_instances().json()
    delete_all.__route_path__ = '/delete-all'

    def setup_routes(self):
        self.add_route_get   (self.list_instances)
        self.add_route_get   (self.info          )
        self.add_route_post  (self.create        )
        self.add_route_post  (self.create_named  )
        self.add_route_delete(self.delete        )
        self.add_route_delete(self.delete_all    )
