# ═══════════════════════════════════════════════════════════════════════════════
# SP CLI — Schema__Stack__Create__Request__Base
# Unified envelope for all per-plugin stack-creation requests.
# Per-plugin schemas extend this base and add plugin-specific fields.
# ═══════════════════════════════════════════════════════════════════════════════

from osbot_utils.type_safe.Type_Safe                                                    import Type_Safe
from osbot_utils.type_safe.primitives.domains.common.safe_str.Safe_Str__Text            import Safe_Str__Text

from sgraph_ai_service_playwright__cli.catalog.enums.Enum__Instance__Size               import Enum__Instance__Size
from sgraph_ai_service_playwright__cli.catalog.enums.Enum__Stack__Creation_Mode         import Enum__Stack__Creation_Mode
from sgraph_ai_service_playwright__cli.catalog.primitives.Safe_Int__Timeout__Minutes    import Safe_Int__Timeout__Minutes
from sgraph_ai_service_playwright__cli.catalog.primitives.Safe_Str__AWS__AMI_Id         import Safe_Str__AWS__AMI_Id


class Schema__Stack__Create__Request__Base(Type_Safe):
    stack_name      : Safe_Str__Text                                                    # auto-generated by service when empty
    creation_mode   : Enum__Stack__Creation_Mode = Enum__Stack__Creation_Mode.FRESH
    ami_id          : Safe_Str__AWS__AMI_Id                                             # required when creation_mode == FROM_AMI
    instance_size   : Enum__Instance__Size       = Enum__Instance__Size.MEDIUM          # plugin maps to AWS instance type
    timeout_minutes : Safe_Int__Timeout__Minutes                                        # 0 = no auto-terminate; plugin default applied by service
