# ═══════════════════════════════════════════════════════════════════════════════
# SP CLI — CF__Inventory__Dashboard__Builder
# Builds the saved-objects ndjson for the "CloudFront Logs - Inventory Overview"
# dashboard.  Mirrors Default__Dashboard__Generator for the synthetic dataset
# — same legacy `visualization` saved-object type (Vis Editor), same
# deterministic-ids pattern, same Kibana-JSON-as-string conventions.
#
# Lens explicitly avoided.  The synthetic-data slice's debrief (sp-elastic-
# kibana 02-what.md, "Notable bugs") flagged Lens migration footguns as the
# #1 reason hand-rolled saved-objects fail to import.  We stay on Vis Editor.
#
# Five panels, each sourced from the sg-cf-inventory-* data view (time
# field: delivery_at):
#   1. Object count over time          line, count() over date_histogram(delivery_at, hourly)
#   2. Total bytes over time           stacked vertical bar, sum(size_bytes) over hourly histogram, split by terms(delivery_day)
#   3. Object size distribution        vertical bar, count() bucketed on size_bytes (numeric histogram, 50KB interval)
#   4. Storage class breakdown         donut, count() with terms on storage_class.keyword
#   5. Activity by hour of day         horizontal bar, count() with terms on delivery_hour
#
# Layout: 2x2 grid + a full-width fifth row, on Kibana's 48-column canvas.
# ═══════════════════════════════════════════════════════════════════════════════

import json
from typing                                                                         import List

from osbot_utils.type_safe.Type_Safe                                                import Type_Safe
from osbot_utils.type_safe.type_safe_core.decorators.type_safe                      import type_safe

from sgraph_ai_service_playwright__cli.elastic.lets.cf.inventory.service.CF__Inventory__Dashboard__Ids import (
    DASHBOARD_ID, DASHBOARD_TITLE,
    VIS_ID__COUNT_OVER_TIME,
    VIS_ID__BYTES_OVER_TIME,
    VIS_ID__SIZE_DISTRIBUTION,
    VIS_ID__STORAGE_CLASS_BREAKDOWN,
    VIS_ID__TOP_HOURLY_PARTITIONS,
)


DASHBOARD_DESCRIPTION = 'Auto-generated by `sp el lets cf inventory load`. Edit or replace via Kibana UI.'

# Reference name Kibana looks up when resolving the data view on a Vis Editor
# visualization. The legacy convention encodes the path inside the JSON-string
# searchSourceJSON.
DATA_VIEW_REF_NAME    = 'kibanaSavedObjectMeta.searchSourceJSON.index'


def search_source_json() -> str:                                                    # The kibanaSavedObjectMeta.searchSourceJSON value (JSON-encoded string)
    return json.dumps({'query'        : {'language': 'kuery', 'query': ''},
                       'filter'       : []                                  ,
                       'indexRefName' : DATA_VIEW_REF_NAME                  })


def vis_object(vis_id: str, title: str, vis_state: dict, data_view_id: str) -> dict:
    return {
        'id'        : vis_id,
        'type'      : 'visualization',
        'attributes': {
            'title'                 : title,
            'visState'              : json.dumps(vis_state),                         # visState lives as a JSON-encoded string — Kibana convention
            'uiStateJSON'           : '{}',
            'description'           : '',
            'version'               : 1,
            'kibanaSavedObjectMeta' : {'searchSourceJSON': search_source_json()},
        },
        'references': [
            {'name': DATA_VIEW_REF_NAME, 'type': 'index-pattern', 'id': data_view_id},
        ],
    }


# ─── panel 1: object count over time ──────────────────────────────────────────
def vis_count_over_time(data_view_id: str, time_field: str = 'delivery_at') -> dict:
    state = {
        'title' : 'Object count over time',
        'type'  : 'line',
        'params': {
            'type'           : 'line',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Object count'}}],
            'seriesParams'   : [{'show': True, 'type': 'line', 'mode': 'normal',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : False,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
        ],
    }
    return vis_object(VIS_ID__COUNT_OVER_TIME, 'Object count over time', state, data_view_id)


# ─── panel 2: total bytes over time, split by delivery_day ────────────────────
def vis_bytes_over_time(data_view_id: str, time_field: str = 'delivery_at') -> dict:
    state = {
        'title' : 'Total bytes over time (by delivery day)',
        'type'  : 'histogram',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Bytes'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'stacked',
                                  'data': {'label': 'Sum size_bytes', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'sum', 'schema': 'metric',
             'params': {'field': 'size_bytes'}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
            {'id': '3', 'enabled': True, 'type': 'terms', 'schema': 'group',
             'params': {'field': 'delivery_day', 'size': 31,
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__BYTES_OVER_TIME, 'Total bytes over time (by delivery day)', state, data_view_id)


# ─── panel 3: object size distribution ────────────────────────────────────────
def vis_size_distribution(data_view_id: str) -> dict:
    state = {
        'title' : 'Object size distribution',
        'type'  : 'histogram',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100},
                                  'title': {'text': 'Size (bytes)'}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Object count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'normal',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : False,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'histogram', 'schema': 'segment',
             'params': {'field': 'size_bytes', 'interval': 50000,                   # 50 KB buckets — most CF-realtime objects fall in 0–10 KB so this groups the long tail
                        'maxBars': 50, 'min_doc_count': True, 'has_extended_bounds': False,
                        'extended_bounds': {}}},
        ],
    }
    return vis_object(VIS_ID__SIZE_DISTRIBUTION, 'Object size distribution', state, data_view_id)


# ─── panel 4: storage class breakdown ─────────────────────────────────────────
def vis_storage_class_breakdown(data_view_id: str) -> dict:
    state = {
        'title' : 'Storage class breakdown',
        'type'  : 'pie',
        'params': {
            'type'           : 'pie',
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'isDonut'        : True,
            'labels'         : {'show': False, 'values': True, 'last_level': True, 'truncate': 100},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'storage_class', 'size': 12,                       # 11 known storage classes + UNKNOWN
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__STORAGE_CLASS_BREAKDOWN, 'Storage class breakdown', state, data_view_id)


# ─── panel 5: activity by hour of day ─────────────────────────────────────────
# Brief asked for "Top hourly partitions (terms on delivery_year/month/day/hour)"
# but Vis Editor's terms agg works on a single field.  Substituted with a
# terms agg on delivery_hour (0-23) — answers a related and arguably more
# useful operational question: "when does CloudFront see the most traffic?"
def vis_activity_by_hour(data_view_id: str) -> dict:
    state = {
        'title' : 'Activity by hour of day (UTC)',
        'type'  : 'horizontal_bar',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'left', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 200},
                                  'title': {'text': 'Hour (UTC)'}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'BottomAxis-1', 'type': 'value', 'position': 'bottom',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 75, 'filter': True, 'truncate': 100},
                                  'title': {'text': 'Object count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'normal',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : False,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': True},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'delivery_hour', 'size': 24,                       # All 24 hours
                        'order': 'asc', 'orderBy': '_key',                          # Sort by hour for chronological readability (ascending)
                        'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__TOP_HOURLY_PARTITIONS, 'Activity by hour of day (UTC)', state, data_view_id)


# ─── dashboard wrapper ────────────────────────────────────────────────────────
def dashboard(panels_json_string: str) -> dict:
    return {
        'id'   : DASHBOARD_ID,
        'type' : 'dashboard',
        'attributes': {
            'title'                   : DASHBOARD_TITLE,
            'description'             : DASHBOARD_DESCRIPTION,
            'panelsJSON'              : panels_json_string,                          # JSON-string-encoded array — Kibana convention
            'optionsJSON'             : json.dumps({'useMargins': True, 'syncColors': False,
                                                     'syncCursor': True, 'syncTooltips': False,
                                                     'hidePanelTitles': False}),
            'version'                 : 1,
            'timeRestore'             : False,
            'kibanaSavedObjectMeta'   : {'searchSourceJSON': json.dumps({'query': {'language': 'kuery', 'query': ''},
                                                                          'filter': []})},
        },
        'references': [
            {'name': 'panel_p1', 'type': 'visualization', 'id': VIS_ID__COUNT_OVER_TIME         },
            {'name': 'panel_p2', 'type': 'visualization', 'id': VIS_ID__BYTES_OVER_TIME         },
            {'name': 'panel_p3', 'type': 'visualization', 'id': VIS_ID__SIZE_DISTRIBUTION       },
            {'name': 'panel_p4', 'type': 'visualization', 'id': VIS_ID__STORAGE_CLASS_BREAKDOWN },
            {'name': 'panel_p5', 'type': 'visualization', 'id': VIS_ID__TOP_HOURLY_PARTITIONS   },
        ],
    }


def panel(panel_index: str, x: int, y: int, w: int, h: int) -> dict:                # panelRefName = "panel_<panelIndex>" so the dashboard's references array can resolve the visualization id
    return {'version'         : '8.13.4',
            'type'            : 'visualization',
            'gridData'        : {'x': x, 'y': y, 'w': w, 'h': h, 'i': panel_index},
            'panelIndex'      : panel_index,
            'embeddableConfig': {'enhancements': {}},
            'panelRefName'    : f'panel_{panel_index}'}


class CF__Inventory__Dashboard__Builder(Type_Safe):

    @type_safe
    def build_ndjson(self, data_view_id : str ,                                     # Kibana data view UUID — baked into every reference
                            time_field   : str = 'delivery_at'
                       ) -> bytes:
        # Layout: 2x2 grid (panels 1-4) + full-width row (panel 5), on a 48-column canvas
        panels = [panel('p1',  0,  0, 24, 12),
                  panel('p2', 24,  0, 24, 12),
                  panel('p3',  0, 12, 24, 12),
                  panel('p4', 24, 12, 24, 12),
                  panel('p5',  0, 24, 48, 12)]
        panels_json_string = json.dumps(panels)

        objects: List[dict] = [
            vis_count_over_time         (data_view_id, time_field),
            vis_bytes_over_time         (data_view_id, time_field),
            vis_size_distribution       (data_view_id),
            vis_storage_class_breakdown (data_view_id),
            vis_activity_by_hour        (data_view_id),
            dashboard                   (panels_json_string),
        ]
        # ndjson: one JSON object per line, no trailing comma, no enclosing array
        return ('\n'.join(json.dumps(o) for o in objects) + '\n').encode('utf-8')

    def dashboard_id(self) -> str:                                                  # Convenience for callers that want the constant without importing the module
        return DASHBOARD_ID

    def dashboard_title(self) -> str:
        return DASHBOARD_TITLE
