# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — playwright: Playwright__Compose__Template
# Renders the docker-compose.yml the EC2 host writes to /opt/sg-playwright/.
#
# Two shapes, selected by `with_mitmproxy`:
#   default          — host-plane + sg-playwright                 (2 containers)
#   with-mitmproxy   — + agent-mitmproxy                          (3 containers)
#
# Only sg-playwright (:8000) and — when present — agent-mitmproxy's admin API
# (:8001) publish host ports. host-plane stays on the internal sg-net bridge;
# reach it with an SSM port-forward. The mitmproxy proxy port (:8080) is
# docker-network-only — sg-playwright talks to it over sg-net.
#
# All ${...} values are resolved by the compose engine from
# /opt/sg-playwright/.env at `up` time — never interpolated here.
# ═══════════════════════════════════════════════════════════════════════════════

from osbot_utils.type_safe.Type_Safe import Type_Safe

HOST_PLANE_IMAGE = 'sgraph_ai_service_playwright_host'                              # ECR repo — docker-control sidecar (proprietary, ECR-only)
PLAYWRIGHT_IMAGE = 'diniscruz/sg-playwright'                                        # Docker Hub repo — pulled directly, no ECR prefix
                                                                                     # → https://hub.docker.com/r/diniscruz/sg-playwright
                                                                                     # Built + pushed by .github/workflows/ci-pipeline.yml
                                                                                     # (job: build-and-push-playwright-image). NOT mirrored to ECR.
MITMPROXY_IMAGE  = 'agent_mitmproxy'                                                # ECR repo — the intercepting proxy sidecar (proprietary, ECR-only)

_HEADER = '''\
# Generated by Playwright__Compose__Template — do not edit by hand.
services:
'''

_HOST_PLANE = '''
  host-plane:
    image: {ecr_registry}/{host_plane_image}:{image_tag}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}
    networks:
      - sg-net
    restart: unless-stopped
'''

# sg-playwright — Docker Hub image, NO ecr_registry prefix. Proxy wiring
# (DEFAULT_PROXY_URL + IGNORE_HTTPS_ERRORS + depends_on) is emitted only when
# --with-mitmproxy is set.
_SG_PLAYWRIGHT = '''
  sg-playwright:
    image: {playwright_image}:{image_tag}
    ports:
      - "8000:8000"
    environment:
      FAST_API__AUTH__API_KEY__NAME:    ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE:   ${{FAST_API__AUTH__API_KEY__VALUE}}
      SG_PLAYWRIGHT__DEPLOYMENT_TARGET: container{proxy_env}
    networks:
      - sg-net{depends_on}
    restart: unless-stopped
'''

_PROXY_ENV = '''
      SG_PLAYWRIGHT__DEFAULT_PROXY_URL:   http://agent-mitmproxy:8080
      SG_PLAYWRIGHT__IGNORE_HTTPS_ERRORS: 'true\''''

_DEPENDS_ON = '''
    depends_on:
      - agent-mitmproxy'''

# agent-mitmproxy — admin API on :8001, proxy on :8080 (sg-net only).
# {interceptor_block} mounts a baked interceptor when --intercept-script is set;
# empty otherwise (the image's baked default interceptor is used).
_AGENT_MITMPROXY = '''
  agent-mitmproxy:
    image: {ecr_registry}/{mitmproxy_image}:{image_tag}
    ports:
      - "8001:8000"
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}{interceptor_env}
    networks:
      - sg-net{interceptor_volume}
    restart: unless-stopped
'''

_INTERCEPTOR_ENV    = '''
      AGENT_MITMPROXY__INTERCEPTOR_PATH: /app/interceptors/active.py'''

_INTERCEPTOR_VOLUME = '''
    volumes:
      - /opt/sg-playwright/interceptors:/app/interceptors:ro'''

_NETWORKS = '''
networks:
  sg-net:
    driver: bridge
'''


class Playwright__Compose__Template(Type_Safe):

    def render(self, ecr_registry    : str  ,
                     with_mitmproxy  : bool = False                     ,
                     with_intercept  : bool = False                     ,
                     image_tag       : str  = 'latest'                  ,
                     host_plane_image: str  = HOST_PLANE_IMAGE          ,
                     playwright_image: str  = PLAYWRIGHT_IMAGE          ,
                     mitmproxy_image : str  = MITMPROXY_IMAGE            ) -> str:
        proxy_env  = _PROXY_ENV  if with_mitmproxy else ''
        depends_on = _DEPENDS_ON if with_mitmproxy else ''
        parts = [
            _HEADER                                                                          ,
            _HOST_PLANE.format(ecr_registry=ecr_registry, host_plane_image=host_plane_image,
                               image_tag=image_tag)                                          ,
            _SG_PLAYWRIGHT.format(playwright_image=playwright_image,                          # no ecr_registry — sg-playwright is on Docker Hub
                                  image_tag=image_tag, proxy_env=proxy_env,
                                  depends_on=depends_on)                                     ,
        ]
        if with_mitmproxy:
            interceptor_env    = _INTERCEPTOR_ENV    if with_intercept else ''
            interceptor_volume = _INTERCEPTOR_VOLUME if with_intercept else ''
            parts.append(_AGENT_MITMPROXY.format(ecr_registry=ecr_registry,
                                                 mitmproxy_image=mitmproxy_image,
                                                 image_tag=image_tag,
                                                 interceptor_env=interceptor_env,
                                                 interceptor_volume=interceptor_volume))
        parts.append(_NETWORKS)
        return ''.join(parts)
