# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — playwright: Playwright__Compose__Template
# Renders the docker-compose.yml the EC2 host writes to /opt/sg-playwright/.
#
# Two shapes, selected by `with_mitmproxy`:
#   default          — host-plane + sg-playwright                 (2 containers)
#   with-mitmproxy   — + agent-mitmproxy                          (3 containers)
#
# Only sg-playwright (:8000) publishes a host port. host-plane and
# agent-mitmproxy stay on the internal sg-net bridge.
# The mitmproxy proxy port (:8080) is docker-network-only — sg-playwright
# talks to it over sg-net.
#
# Image sources (all Docker Hub — no ECR):
#   host-plane      → diniscruz/sg-host-control  (Docker Hub)
#   sg-playwright   → diniscruz/sg-playwright    (Docker Hub)
#   agent-mitmproxy → mitmproxy/mitmproxy:latest (Docker Hub OSS)
#
# All ${...} values are resolved by the compose engine from
# /opt/sg-playwright/.env at `up` time — never interpolated here.
# ═══════════════════════════════════════════════════════════════════════════════

from osbot_utils.type_safe.Type_Safe import Type_Safe

HOST_PLANE_IMAGE = 'diniscruz/sg-host-control'                                      # Docker Hub — dedicated host-control image (python:3.12-alpine + sg_compute)
                                                                                     # Built + pushed by .github/workflows/build-host-control-dockerhub.yml
PLAYWRIGHT_IMAGE = 'diniscruz/sg-playwright'                                        # Docker Hub repo — pulled directly, no ECR prefix
                                                                                     # → https://hub.docker.com/r/diniscruz/sg-playwright
                                                                                     # Built + pushed by .github/workflows/ci-pipeline.yml
                                                                                     # (job: build-and-push-playwright-image). NOT mirrored to ECR.
MITMPROXY_IMAGE  = 'mitmproxy/mitmproxy:latest'                                     # Docker Hub OSS image — no custom build required

_HEADER = '''\
# Generated by Playwright__Compose__Template — do not edit by hand.
services:
'''

_HOST_PLANE = '''
  host-plane:
    image: {host_plane_image}:{image_tag}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FAST_API__AUTH__API_KEY__NAME:  ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE: ${{FAST_API__AUTH__API_KEY__VALUE}}
    networks:
      - sg-net
    restart: unless-stopped
'''

# sg-playwright — Docker Hub image, NO ecr_registry prefix. Proxy wiring
# (DEFAULT_PROXY_URL + IGNORE_HTTPS_ERRORS + depends_on) is emitted only when
# --with-mitmproxy is set.
_SG_PLAYWRIGHT = '''
  sg-playwright:
    image: {playwright_image}:{image_tag}
    ports:
      - "8000:8000"
    environment:
      FAST_API__AUTH__API_KEY__NAME:    ${{FAST_API__AUTH__API_KEY__NAME:-X-API-Key}}
      FAST_API__AUTH__API_KEY__VALUE:   ${{FAST_API__AUTH__API_KEY__VALUE}}
      SG_PLAYWRIGHT__DEPLOYMENT_TARGET: container{proxy_env}
    networks:
      - sg-net{depends_on}
    restart: unless-stopped
'''

_PROXY_ENV = '''
      SG_PLAYWRIGHT__DEFAULT_PROXY_URL:   http://agent-mitmproxy:8080
      SG_PLAYWRIGHT__IGNORE_HTTPS_ERRORS: 'true\''''

_DEPENDS_ON = '''
    depends_on:
      - agent-mitmproxy'''

# agent-mitmproxy — OSS mitmproxy from Docker Hub. Proxy on :8080 (sg-net only).
# mitmweb UI bound to 127.0.0.1:8081 (loopback inside container — not published).
# {script_args} appends -s /interceptors/active.py when --intercept-script is set.
_AGENT_MITMPROXY = '''
  agent-mitmproxy:
    image: {mitmproxy_image}
    command:
      - mitmweb
      - --web-host=127.0.0.1
      - --web-port=8081
      - --listen-host=0.0.0.0
      - --listen-port=8080
      - --set
      - block_global=false{script_args}
    networks:
      - sg-net{interceptor_volume}
    restart: unless-stopped
'''

_SCRIPT_ARGS = '''
      - -s
      - /interceptors/active.py'''

_INTERCEPTOR_VOLUME = '''
    volumes:
      - /opt/sg-playwright/interceptors:/interceptors:ro'''

_NETWORKS = '''
networks:
  sg-net:
    driver: bridge
'''


class Playwright__Compose__Template(Type_Safe):

    def render(self, with_mitmproxy  : bool = False                     ,
                     with_intercept  : bool = False                     ,
                     image_tag       : str  = 'latest'                  ,
                     host_plane_image: str  = HOST_PLANE_IMAGE          ,
                     playwright_image: str  = PLAYWRIGHT_IMAGE          ,
                     mitmproxy_image : str  = MITMPROXY_IMAGE            ) -> str:
        proxy_env  = _PROXY_ENV  if with_mitmproxy else ''
        depends_on = _DEPENDS_ON if with_mitmproxy else ''
        parts = [
            _HEADER                                                                          ,
            _HOST_PLANE.format(host_plane_image=host_plane_image, image_tag=image_tag)       ,
            _SG_PLAYWRIGHT.format(playwright_image=playwright_image,
                                  image_tag=image_tag, proxy_env=proxy_env,
                                  depends_on=depends_on)                                     ,
        ]
        if with_mitmproxy:
            script_args       = _SCRIPT_ARGS       if with_intercept else ''
            interceptor_volume = _INTERCEPTOR_VOLUME if with_intercept else ''
            parts.append(_AGENT_MITMPROXY.format(mitmproxy_image=mitmproxy_image,
                                                 script_args=script_args,
                                                 interceptor_volume=interceptor_volume))
        parts.append(_NETWORKS)
        return ''.join(parts)
