# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — vault-publish setup: Setup__CF__Function
# Drift-check + create for the CloudFront Function that copies the viewer Host
# header into X-Forwarded-Host before CloudFront forwards to the Lambda
# Function URL origin. Without this, the waker only ever sees the Lambda URL
# hostname and can never parse a slug.
#
# Function name : vault-publish-viewer-host
# Runtime       : cloudfront-js-2.0
# Event type    : viewer-request (runs at CF edge before origin fetch)
#
# Tracing headers added by the function on every request:
#   x-waker-flow-id      — unique per-request ID (timestamp + random)
#   x-waker-cf-timestamp — ISO-8601 timestamp from the CF edge
#   x-waker-cf-version   — value of FUNCTION_VERSION below
#
# >>> BUMP FUNCTION_VERSION ON EVERY JS CHANGE (the .y in v0.x.y). <<<
# This forces the live LIVE-stage code to differ from the previous version,
# which triggers republish+attach on the next `setup cf-function update`.
#
# Async by design: attach_function_to_distribution() returns immediately;
# CloudFront edge propagation takes ~5min and is intentionally not awaited
# (run `sg vp setup cf-function check` later to verify, or use the AWS
# console to watch propagation).
#
# Mutation gate: SG_AWS__VAULT_PUBLISH__SETUP__ALLOW_MUTATIONS=1
# Delete gate:   SG_AWS__VAULT_PUBLISH__SETUP__ALLOW_DELETES=1
# ═══════════════════════════════════════════════════════════════════════════════

import os
from typing import Callable, Optional

from osbot_utils.type_safe.Type_Safe import Type_Safe

from sg_compute_specs.vault_publish.setup.collections.List__Schema__Setup__Issue       import List__Schema__Setup__Issue
from sg_compute_specs.vault_publish.setup.schemas.Enum__Setup__State                   import Enum__Setup__State
from sg_compute_specs.vault_publish.setup.schemas.Schema__Setup__Issue                 import Schema__Setup__Issue
from sg_compute_specs.vault_publish.setup.schemas.Schema__Setup__CF_Function__Report   import Schema__Setup__CF_Function__Report

FUNCTION_NAME    = 'vault-publish-viewer-host'
FUNCTION_COMMENT = 'Vault Publish — viewer-Host shim + tracing headers'
FUNCTION_RUNTIME = 'cloudfront-js-2.0'
EVENT_TYPE       = 'viewer-request'

FUNCTION_VERSION = 'v0.0.1'                                                            # bump .y on every JS change below

# _normalise() strips all whitespace so reformatting doesn't trigger drift.
# Date.now()+Math.random() flow-id avoids requiring crypto.* in the runtime.
FUNCTION_CODE = ("""\
// vault-publish-viewer-host — version {{VERSION}}
// Generated by sg_compute_specs/vault_publish/setup/service/Setup__CF__Function.py
// Bump FUNCTION_VERSION (Python) on every change here.
function handler(event) {
    var req = event.request;
    var now = new Date();

    // 1. Preserve viewer Host before CloudFront rewrites it to the Lambda URL.
    if (req.headers.host) {
        req.headers['x-forwarded-host'] = { value: req.headers.host.value };
    }

    // 2. Tracing headers — the waker Lambda echoes these as X-Waker-* response
    //    headers so the full edge → Lambda → vault-app flow can be traced.
    var flowId = Date.now().toString(36) + '-' + Math.floor(Math.random() * 1e9).toString(36);
    req.headers['x-waker-flow-id']      = { value: flowId };
    req.headers['x-waker-cf-timestamp'] = { value: now.toISOString() };
    req.headers['x-waker-cf-version']   = { value: '{{VERSION}}' };

    return req;
}
""").replace('{{VERSION}}', FUNCTION_VERSION)


class Setup__CF__Function(Type_Safe):
    _fn_client_factory   : Optional[Callable] = None
    _cf_client_factory   : Optional[Callable] = None

    def _fn_client(self):
        if self._fn_client_factory:
            return self._fn_client_factory()
        from sgraph_ai_service_playwright__cli.aws.cf.service.CloudFront__Function__AWS__Client import CloudFront__Function__AWS__Client
        return CloudFront__Function__AWS__Client()

    def _cf_client(self):
        if self._cf_client_factory:
            return self._cf_client_factory()
        from sgraph_ai_service_playwright__cli.aws.cf.service.CloudFront__AWS__Client import CloudFront__AWS__Client
        return CloudFront__AWS__Client()

    # ── read ─────────────────────────────────────────────────────────────────

    def check(self, zone: str) -> Schema__Setup__CF_Function__Report:
        issues = List__Schema__Setup__Issue()
        fn     = self._fn_client().describe(FUNCTION_NAME, stage='LIVE')
        if not fn.exists:
            issues.append(Schema__Setup__Issue(
                severity='error', area='cf-function',
                message=f'CloudFront Function {FUNCTION_NAME!r} not deployed'))
            return Schema__Setup__CF_Function__Report(
                state=Enum__Setup__State.MISSING, zone=zone,
                function_name=FUNCTION_NAME, issues=issues)

        live_code    = self._fn_client().get_code(FUNCTION_NAME, stage='LIVE')
        code_matches = _normalise(live_code) == _normalise(FUNCTION_CODE)
        if not code_matches:
            issues.append(Schema__Setup__Issue(
                severity='warn', area='cf-function',
                message=f'live code differs from expected ({len(live_code)}b vs {len(FUNCTION_CODE)}b) '
                        '— run `sg vp setup cf-function show` for the diff, then `update` to fix'))
            hint = _first_diff_hint(live_code, FUNCTION_CODE)
            if hint:
                issues.append(Schema__Setup__Issue(severity='info', area='cf-function', message=hint))

        # Check distribution association
        attached    = False
        dist_id     = ''
        cf_dist     = self._cf_client().find_distribution_by_alias(f'*.{zone}')
        if cf_dist:
            dist_id  = str(cf_dist.distribution_id)
            attached = self._is_attached(dist_id, fn.arn)
            if not attached:
                issues.append(Schema__Setup__Issue(
                    severity='error', area='cf-function',
                    message=f'function not attached to distribution {dist_id} on {EVENT_TYPE}'))
        else:
            issues.append(Schema__Setup__Issue(
                severity='warn', area='cf-function',
                message=f'no CloudFront distribution for *.{zone} — cannot check attachment'))

        state = (Enum__Setup__State.OK if (code_matches and attached) else Enum__Setup__State.DRIFT)
        return Schema__Setup__CF_Function__Report(
            state           = state,
            zone            = zone,
            function_name   = FUNCTION_NAME,
            function_arn    = fn.arn,
            function_exists = True,
            function_stage  = fn.stage,
            code_matches    = code_matches,
            attached        = attached,
            distribution_id = dist_id,
            issues          = issues,
        )

    def status(self, zone: str) -> dict:
        fn = self._fn_client().describe(FUNCTION_NAME, stage='LIVE')
        if not fn.exists:
            return {'function_name': FUNCTION_NAME, 'exists': 'no'}
        dist_id  = ''
        attached = 'unknown'
        cf_dist  = self._cf_client().find_distribution_by_alias(f'*.{zone}')
        if cf_dist:
            dist_id  = str(cf_dist.distribution_id)
            attached = 'yes' if self._is_attached(dist_id, fn.arn) else 'no'
        return {
            'function_name'  : FUNCTION_NAME,
            'function_arn'   : fn.arn,
            'stage'          : fn.stage,
            'status'         : fn.status,
            'runtime'        : fn.runtime,
            'last_modified'  : fn.last_modified,
            'distribution_id': dist_id or '(none)',
            'attached'       : attached,
        }

    # ── mutations ─────────────────────────────────────────────────────────────

    def create(self, zone: str) -> Schema__Setup__CF_Function__Report:
        _require_mutations()
        fn_client = self._fn_client()

        # 1. ensure the DEVELOPMENT function exists with the expected code
        dev = fn_client.describe(FUNCTION_NAME, stage='DEVELOPMENT')
        if not dev.exists:
            fn_client.create(FUNCTION_NAME, code=FUNCTION_CODE,
                             comment=FUNCTION_COMMENT, runtime=FUNCTION_RUNTIME)
            dev = fn_client.describe(FUNCTION_NAME, stage='DEVELOPMENT')
        else:
            live_dev = fn_client.get_code(FUNCTION_NAME, stage='DEVELOPMENT')
            if _normalise(live_dev) != _normalise(FUNCTION_CODE):
                fn_client.update(FUNCTION_NAME, code=FUNCTION_CODE, etag=dev.etag,
                                 comment=FUNCTION_COMMENT, runtime=FUNCTION_RUNTIME)
                dev = fn_client.describe(FUNCTION_NAME, stage='DEVELOPMENT')

        # 2. publish DEVELOPMENT → LIVE
        fn_client.publish(FUNCTION_NAME, etag=dev.etag)
        live = fn_client.describe(FUNCTION_NAME, stage='LIVE')

        # 3. attach to the wildcard distribution (async — edge propagation ~5min)
        cf_dist = self._cf_client().find_distribution_by_alias(f'*.{zone}')
        if cf_dist:
            self._cf_client().attach_function_to_distribution(
                str(cf_dist.distribution_id), live.arn, event_type=EVENT_TYPE)

        return self.check(zone)

    def update(self, zone: str) -> Schema__Setup__CF_Function__Report:
        _require_mutations()
        return self.create(zone)                                                       # same flow — create() handles ensure+publish+attach

    def delete(self, zone: str) -> bool:
        _require_deletes()
        fn_client = self._fn_client()

        # 1. detach from the distribution (if any)
        cf_dist = self._cf_client().find_distribution_by_alias(f'*.{zone}')
        if cf_dist:
            try:
                self._cf_client().detach_function_from_distribution(
                    str(cf_dist.distribution_id), event_type=EVENT_TYPE)
            except Exception:
                pass

        # 2. delete the function — must use DEVELOPMENT etag and the function
        # must be UNASSOCIATED (post-edge-propagation). This commonly fails
        # for ~5min after detach; the operator can re-run later.
        for stage in ('DEVELOPMENT', 'LIVE'):
            meta = fn_client.describe(FUNCTION_NAME, stage=stage)
            if meta.exists and meta.etag:
                fn_client.delete(FUNCTION_NAME, etag=meta.etag)
        gone = not fn_client.describe(FUNCTION_NAME, stage='LIVE').exists
        return gone

    # ── internal ─────────────────────────────────────────────────────────────

    def _is_attached(self, distribution_id: str, function_arn: str) -> bool:
        try:
            arns = self._cf_client().get_function_associations(
                distribution_id, event_type=EVENT_TYPE)
        except Exception:
            return False
        # CloudFront Function ARNs have the form
        #   arn:aws:cloudfront::<acct>:function/<name>
        # (colon-function-slash-name, NOT slash-function-slash). Match by the
        # `:function/<name>` suffix so we tolerate any account / region
        # variation and any version qualifier AWS may append.
        suffix = f':function/{FUNCTION_NAME}'
        return any(suffix in a for a in arns)


def _normalise(code: str) -> str:
    # Strip whitespace differences so cosmetic edits don't trigger drift.
    return ''.join(code.split())


def _first_diff_hint(live: str, expected: str) -> str:
    # Compare normalised forms — that's what triggers the drift flag.
    n_live = _normalise(live)
    n_exp  = _normalise(expected)
    if n_live == n_exp:
        return ''
    # Find first divergent character; show ~20 chars of context each side.
    limit = min(len(n_live), len(n_exp))
    i = next((k for k in range(limit) if n_live[k] != n_exp[k]), limit)
    a = i - 20 if i > 20 else 0
    b = i + 30
    return (f'first diff @ char {i} (normalised): '
            f'expected …{n_exp[a:b]!r}  live …{n_live[a:b]!r}')


# ── gates ─────────────────────────────────────────────────────────────────────

def _require_mutations():
    if not os.environ.get('SG_AWS__VAULT_PUBLISH__SETUP__ALLOW_MUTATIONS'):
        raise RuntimeError(
            'Set SG_AWS__VAULT_PUBLISH__SETUP__ALLOW_MUTATIONS=1 to allow CF Function mutations')


def _require_deletes():
    if not os.environ.get('SG_AWS__VAULT_PUBLISH__SETUP__ALLOW_DELETES'):
        raise RuntimeError(
            'Set SG_AWS__VAULT_PUBLISH__SETUP__ALLOW_DELETES=1 to allow CF Function deletes')
