# ═══════════════════════════════════════════════════════════════════════════════
# SP CLI — Default__Dashboard__Generator
# Builds the saved-objects ndjson for the "Synthetic Logs Overview" dashboard
# that `sp el seed` creates by default. Programmatic generation rather than a
# checked-in fixture file because every panel needs the data view id baked
# into its `references` array — the id is unknown until ensure_data_view ran.
#
# We use the legacy `visualization` saved-object type (Vis Editor) rather than
# Lens. Reasons:
#   - The Lens saved-object format has many migration hooks that crash with
#     HTTP 500 on hand-rolled JSON without a real export to clone from.
#   - Vis Editor is technically deprecated in 8.x but still fully supported
#     and far more forgiving — its `visState` is a single JSON-encoded string
#     defining the chart type, params, and aggregations.
#
# Output panels (visualization type, all sourced from the data view):
#   1. Log levels                  — donut, terms on level.keyword
#   2. Log volume over time        — stacked vertical bar, date_histogram on
#                                    timestamp, split by level.keyword
#   3. Top services                — horizontal bar, terms on service.keyword
#   4. Average duration over time  — line, date_histogram + avg(duration_ms)
#
# IDs are deterministic so re-running seed with overwrite=true is idempotent.
# ═══════════════════════════════════════════════════════════════════════════════

import json
from typing                                                                         import List

from osbot_utils.type_safe.Type_Safe                                                import Type_Safe
from osbot_utils.type_safe.type_safe_core.decorators.type_safe                      import type_safe


DASHBOARD_ID                  = 'sg-synthetic-overview'
DASHBOARD_TITLE               = 'Synthetic Logs Overview'
DASHBOARD_DESCRIPTION         = 'Auto-generated by `sp el seed`. Edit or replace via Kibana UI.'

VIS_ID__LOG_LEVELS            = 'sg-vis-log-levels'
VIS_ID__VOLUME_BY_LEVEL       = 'sg-vis-volume-by-level'
VIS_ID__TOP_SERVICES          = 'sg-vis-top-services'
VIS_ID__AVG_DURATION          = 'sg-vis-avg-duration'

# Old IDs from the first Lens-based attempt — still listed so that `wipe` and
# the pre-import cleanup remove any stale half-migrated documents Kibana
# would otherwise keep choking on (savedobjects-service: "Cannot read
# properties of undefined").
LEGACY_LENS_IDS = ['sg-lens-log-levels', 'sg-lens-volume-by-level',
                    'sg-lens-top-services', 'sg-lens-avg-duration']

# Every saved object related to the default dashboard, by (type, id) — the
# canonical list used to clean state before re-import and during `sp el wipe`.
def all_dashboard_object_refs() -> list:
    return ([('dashboard'    , DASHBOARD_ID            )]
          + [('visualization', VIS_ID__LOG_LEVELS      ),
             ('visualization', VIS_ID__VOLUME_BY_LEVEL ),
             ('visualization', VIS_ID__TOP_SERVICES    ),
             ('visualization', VIS_ID__AVG_DURATION    )]
          + [('lens', lid) for lid in LEGACY_LENS_IDS])


# Reference name Kibana looks up when resolving the data view on a Vis Editor
# visualization. The legacy convention encodes the path inside the JSON-string
# searchSourceJSON.
DATA_VIEW_REF_NAME            = 'kibanaSavedObjectMeta.searchSourceJSON.index'


def _search_source_json() -> str:                                                   # The kibanaSavedObjectMeta.searchSourceJSON value (JSON-encoded string). The data view is referenced by name, not by id.
    return json.dumps({'query'        : {'language': 'kuery', 'query': ''},
                       'filter'       : []                                  ,
                       'indexRefName' : DATA_VIEW_REF_NAME                  })


def _vis_object(vis_id: str, title: str, vis_state: dict, data_view_id: str) -> dict:
    return {
        'id'        : vis_id,
        'type'      : 'visualization',
        'attributes': {
            'title'                 : title,
            'visState'              : json.dumps(vis_state),                         # visState lives as a JSON-encoded string — Kibana convention
            'uiStateJSON'           : '{}',
            'description'           : '',
            'version'               : 1,
            'kibanaSavedObjectMeta' : {'searchSourceJSON': _search_source_json()},
        },
        'references': [
            {'name': DATA_VIEW_REF_NAME, 'type': 'index-pattern', 'id': data_view_id},
        ],
    }


def vis_log_levels(data_view_id: str) -> dict:                                      # Donut by level.keyword
    state = {
        'title' : 'Log levels',
        'type'  : 'pie',
        'params': {
            'type'           : 'pie',
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'isDonut'        : True,
            'labels'         : {'show': False, 'values': True, 'last_level': True, 'truncate': 100},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'level.keyword', 'size': 10,
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return _vis_object(VIS_ID__LOG_LEVELS, 'Log levels', state, data_view_id)


def vis_volume_by_level(data_view_id: str, time_field: str) -> dict:                # Stacked vertical bar over time, split by level.keyword
    state = {
        'title' : 'Log volume over time (by level)',
        'type'  : 'histogram',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'stacked',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
            {'id': '3', 'enabled': True, 'type': 'terms', 'schema': 'group',
             'params': {'field': 'level.keyword', 'size': 5,
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return _vis_object(VIS_ID__VOLUME_BY_LEVEL, 'Log volume over time (by level)', state, data_view_id)


def vis_top_services(data_view_id: str) -> dict:                                    # Horizontal bar, terms on service.keyword
    state = {
        'title' : 'Top services',
        'type'  : 'horizontal_bar',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'left', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 200}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'BottomAxis-1', 'type': 'value', 'position': 'bottom',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 75, 'filter': True, 'truncate': 100},
                                  'title': {'text': 'Count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'normal',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : False,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': True},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'service.keyword', 'size': 10,
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return _vis_object(VIS_ID__TOP_SERVICES, 'Top services', state, data_view_id)


def vis_avg_duration(data_view_id: str, time_field: str) -> dict:                   # Line of avg(duration_ms) over time
    state = {
        'title' : 'Average request duration over time',
        'type'  : 'line',
        'params': {
            'type'           : 'line',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Avg duration_ms'}}],
            'seriesParams'   : [{'show': True, 'type': 'line', 'mode': 'normal',
                                  'data': {'label': 'Avg duration_ms', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : False,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'avg', 'schema': 'metric',
             'params': {'field': 'duration_ms'}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
        ],
    }
    return _vis_object(VIS_ID__AVG_DURATION, 'Average request duration over time', state, data_view_id)


def dashboard(panels_json_string: str) -> dict:
    return {
        'id'   : DASHBOARD_ID,
        'type' : 'dashboard',
        'attributes': {
            'title'                   : DASHBOARD_TITLE,
            'description'             : DASHBOARD_DESCRIPTION,
            'panelsJSON'              : panels_json_string,                          # JSON-string-encoded array — Kibana convention
            'optionsJSON'             : json.dumps({'useMargins': True, 'syncColors': False,
                                                     'syncCursor': True, 'syncTooltips': False,
                                                     'hidePanelTitles': False}),
            'version'                 : 1,
            'timeRestore'             : False,
            'kibanaSavedObjectMeta'   : {'searchSourceJSON': json.dumps({'query': {'language': 'kuery', 'query': ''},
                                                                          'filter': []})},
        },
        'references': [
            {'name': 'panel_p1', 'type': 'visualization', 'id': VIS_ID__LOG_LEVELS     },
            {'name': 'panel_p2', 'type': 'visualization', 'id': VIS_ID__VOLUME_BY_LEVEL},
            {'name': 'panel_p3', 'type': 'visualization', 'id': VIS_ID__TOP_SERVICES   },
            {'name': 'panel_p4', 'type': 'visualization', 'id': VIS_ID__AVG_DURATION   },
        ],
    }


def panel(panel_index: str, x: int, y: int, w: int, h: int) -> dict:                # Convention: panelRefName = "panel_<panelIndex>" so the dashboard's references array can resolve the visualization id
    return {'version'         : '8.13.4',
            'type'            : 'visualization',
            'gridData'        : {'x': x, 'y': y, 'w': w, 'h': h, 'i': panel_index},
            'panelIndex'      : panel_index,
            'embeddableConfig': {'enhancements': {}},
            'panelRefName'    : f'panel_{panel_index}'}


class Default__Dashboard__Generator(Type_Safe):

    @type_safe
    def build_ndjson(self, index        : str ,                                     # ES index name (also the data view title)
                            data_view_id : str ,                                     # Kibana data view UUID — baked into every reference
                            time_field   : str = 'timestamp'
                       ) -> bytes:
        # Layout: 2x2 grid, each panel 24w x 12h on a 48-column canvas
        panels = [panel('p1',  0,  0, 24, 12),
                  panel('p2', 24,  0, 24, 12),
                  panel('p3',  0, 12, 24, 12),
                  panel('p4', 24, 12, 24, 12)]
        panels_json_string = json.dumps(panels)

        objects: List[dict] = [
            vis_log_levels     (data_view_id),
            vis_volume_by_level(data_view_id, time_field),
            vis_top_services   (data_view_id),
            vis_avg_duration   (data_view_id, time_field),
            dashboard          (panels_json_string),
        ]
        # ndjson: one JSON object per line, no trailing comma, no enclosing array
        return ('\n'.join(json.dumps(o) for o in objects) + '\n').encode('utf-8')

    def dashboard_id(self) -> str:                                                  # So callers can render it without importing the module-level constant
        return DASHBOARD_ID

    def dashboard_title(self) -> str:
        return DASHBOARD_TITLE
