# ═══════════════════════════════════════════════════════════════════════════════
# SP CLI — Default__Dashboard__Generator
# Builds the saved-objects ndjson for the "Synthetic Logs Overview" dashboard
# that `sp el seed` creates by default. Programmatic generation rather than a
# checked-in fixture file because every panel needs the data view id baked
# into its `references` array — the id is unknown until ensure_data_view ran.
#
# Output panels (Lens, formBased datasource):
#   1. Log levels                  — donut, terms on level.keyword
#   2. Log volume over time        — stacked bar, date_histogram on timestamp,
#                                    split by level.keyword
#   3. Top services                — horizontal bar, terms on service.keyword
#   4. Average duration over time  — line, date_histogram + avg(duration_ms)
#
# IDs are deterministic so re-running seed with overwrite=true is idempotent.
# ═══════════════════════════════════════════════════════════════════════════════

import json
from typing                                                                         import List

from osbot_utils.type_safe.Type_Safe                                                import Type_Safe
from osbot_utils.type_safe.type_safe_core.decorators.type_safe                      import type_safe


DASHBOARD_ID                  = 'sg-synthetic-overview'
DASHBOARD_TITLE               = 'Synthetic Logs Overview'
DASHBOARD_DESCRIPTION         = 'Auto-generated by `sp el seed`. Edit or replace via Kibana UI.'

LENS_ID__LOG_LEVELS           = 'sg-lens-log-levels'
LENS_ID__VOLUME_BY_LEVEL      = 'sg-lens-volume-by-level'
LENS_ID__TOP_SERVICES         = 'sg-lens-top-services'
LENS_ID__AVG_DURATION         = 'sg-lens-avg-duration'


def lens_log_levels(data_view_id: str) -> dict:                                     # Donut by level.keyword
    return {
        'id'   : LENS_ID__LOG_LEVELS,
        'type' : 'lens',
        'attributes': {
            'title'             : 'Log levels',
            'description'       : '',
            'visualizationType' : 'lnsPie',
            'state': {
                'datasourceStates': {'formBased': {'layers': {'layer-1': {
                    'columnOrder': ['col-bucket', 'col-count'],
                    'columns': {
                        'col-bucket': {'operationType': 'terms', 'sourceField': 'level.keyword',
                                        'label': 'Top values of level', 'dataType': 'string', 'isBucketed': True,
                                        'params': {'size': 10, 'orderBy': {'type': 'column', 'columnId': 'col-count'},
                                                   'orderDirection': 'desc', 'otherBucket': True, 'missingBucket': False}},
                        'col-count' : {'operationType': 'count', 'sourceField': '___records___',
                                        'label': 'Count', 'dataType': 'number', 'isBucketed': False,
                                        'params': {}},
                    },
                }}}},
                'visualization': {
                    'shape' : 'donut',
                    'layers': [{'layerId': 'layer-1', 'layerType': 'data',
                                'primaryGroups': ['col-bucket'], 'metrics': ['col-count'],
                                'numberDisplay': 'percent', 'categoryDisplay': 'default',
                                'legendDisplay': 'default'}],
                },
                'filters': [], 'query': {'language': 'kuery', 'query': ''},
            },
        },
        'references': [{'name': 'indexpattern-datasource-layer-layer-1',
                         'type': 'index-pattern', 'id': data_view_id}],
    }


def lens_volume_by_level(data_view_id: str, time_field: str) -> dict:               # Stacked bar over time, split by level.keyword
    return {
        'id'   : LENS_ID__VOLUME_BY_LEVEL,
        'type' : 'lens',
        'attributes': {
            'title'             : 'Log volume over time (by level)',
            'description'       : '',
            'visualizationType' : 'lnsXY',
            'state': {
                'datasourceStates': {'formBased': {'layers': {'layer-1': {
                    'columnOrder': ['col-time', 'col-split', 'col-count'],
                    'columns': {
                        'col-time'  : {'operationType': 'date_histogram', 'sourceField': time_field,
                                        'label': time_field, 'dataType': 'date', 'isBucketed': True,
                                        'params': {'interval': 'auto', 'includeEmptyRows': True, 'dropPartials': False}},
                        'col-split' : {'operationType': 'terms', 'sourceField': 'level.keyword',
                                        'label': 'Top values of level', 'dataType': 'string', 'isBucketed': True,
                                        'params': {'size': 5, 'orderBy': {'type': 'column', 'columnId': 'col-count'},
                                                   'orderDirection': 'desc', 'otherBucket': False, 'missingBucket': False}},
                        'col-count' : {'operationType': 'count', 'sourceField': '___records___',
                                        'label': 'Count', 'dataType': 'number', 'isBucketed': False, 'params': {}},
                    },
                }}}},
                'visualization': {
                    'preferredSeriesType': 'bar_stacked',
                    'legend' : {'isVisible': True, 'position': 'right'},
                    'valueLabels': 'hide',
                    'fittingFunction': 'None',
                    'axisTitlesVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'tickLabelsVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'gridlinesVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'layers': [{'layerId': 'layer-1', 'layerType': 'data',
                                'seriesType': 'bar_stacked',
                                'xAccessor': 'col-time',
                                'splitAccessor': 'col-split',
                                'accessors': ['col-count']}],
                },
                'filters': [], 'query': {'language': 'kuery', 'query': ''},
            },
        },
        'references': [{'name': 'indexpattern-datasource-layer-layer-1',
                         'type': 'index-pattern', 'id': data_view_id}],
    }


def lens_top_services(data_view_id: str) -> dict:                                   # Horizontal bar, terms on service.keyword
    return {
        'id'   : LENS_ID__TOP_SERVICES,
        'type' : 'lens',
        'attributes': {
            'title'             : 'Top services',
            'description'       : '',
            'visualizationType' : 'lnsXY',
            'state': {
                'datasourceStates': {'formBased': {'layers': {'layer-1': {
                    'columnOrder': ['col-bucket', 'col-count'],
                    'columns': {
                        'col-bucket': {'operationType': 'terms', 'sourceField': 'service.keyword',
                                        'label': 'Top values of service', 'dataType': 'string', 'isBucketed': True,
                                        'params': {'size': 10, 'orderBy': {'type': 'column', 'columnId': 'col-count'},
                                                   'orderDirection': 'desc', 'otherBucket': False, 'missingBucket': False}},
                        'col-count' : {'operationType': 'count', 'sourceField': '___records___',
                                        'label': 'Count', 'dataType': 'number', 'isBucketed': False, 'params': {}},
                    },
                }}}},
                'visualization': {
                    'preferredSeriesType': 'bar_horizontal',
                    'legend' : {'isVisible': False, 'position': 'right'},
                    'valueLabels': 'show',
                    'fittingFunction': 'None',
                    'axisTitlesVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'tickLabelsVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'gridlinesVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'layers': [{'layerId': 'layer-1', 'layerType': 'data',
                                'seriesType': 'bar_horizontal',
                                'xAccessor': 'col-bucket',
                                'accessors': ['col-count']}],
                },
                'filters': [], 'query': {'language': 'kuery', 'query': ''},
            },
        },
        'references': [{'name': 'indexpattern-datasource-layer-layer-1',
                         'type': 'index-pattern', 'id': data_view_id}],
    }


def lens_avg_duration(data_view_id: str, time_field: str) -> dict:                  # Line of avg(duration_ms) over time
    return {
        'id'   : LENS_ID__AVG_DURATION,
        'type' : 'lens',
        'attributes': {
            'title'             : 'Average request duration over time',
            'description'       : '',
            'visualizationType' : 'lnsXY',
            'state': {
                'datasourceStates': {'formBased': {'layers': {'layer-1': {
                    'columnOrder': ['col-time', 'col-avg'],
                    'columns': {
                        'col-time': {'operationType': 'date_histogram', 'sourceField': time_field,
                                      'label': time_field, 'dataType': 'date', 'isBucketed': True,
                                      'params': {'interval': 'auto', 'includeEmptyRows': True, 'dropPartials': False}},
                        'col-avg' : {'operationType': 'average', 'sourceField': 'duration_ms',
                                      'label': 'Avg duration_ms', 'dataType': 'number', 'isBucketed': False,
                                      'params': {}},
                    },
                }}}},
                'visualization': {
                    'preferredSeriesType': 'line',
                    'legend' : {'isVisible': False, 'position': 'right'},
                    'valueLabels': 'hide',
                    'fittingFunction': 'None',
                    'axisTitlesVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'tickLabelsVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'gridlinesVisibilitySettings': {'x': True, 'yLeft': True, 'yRight': True},
                    'layers': [{'layerId': 'layer-1', 'layerType': 'data',
                                'seriesType': 'line',
                                'xAccessor': 'col-time',
                                'accessors': ['col-avg']}],
                },
                'filters': [], 'query': {'language': 'kuery', 'query': ''},
            },
        },
        'references': [{'name': 'indexpattern-datasource-layer-layer-1',
                         'type': 'index-pattern', 'id': data_view_id}],
    }


def dashboard(panels_json_string: str) -> dict:
    return {
        'id'   : DASHBOARD_ID,
        'type' : 'dashboard',
        'attributes': {
            'title'                   : DASHBOARD_TITLE,
            'description'             : DASHBOARD_DESCRIPTION,
            'panelsJSON'              : panels_json_string,                          # JSON-string-encoded array — Kibana convention
            'optionsJSON'             : json.dumps({'useMargins': True, 'syncColors': False,
                                                     'syncCursor': True, 'syncTooltips': False,
                                                     'hidePanelTitles': False}),
            'version'                 : 1,
            'timeRestore'             : False,
            'kibanaSavedObjectMeta'   : {'searchSourceJSON': json.dumps({'query': {'language': 'kuery', 'query': ''},
                                                                          'filter': []})},
        },
        'references': [
            {'name': 'panel_lens-log-levels'      , 'type': 'lens', 'id': LENS_ID__LOG_LEVELS     },
            {'name': 'panel_lens-volume-by-level' , 'type': 'lens', 'id': LENS_ID__VOLUME_BY_LEVEL},
            {'name': 'panel_lens-top-services'    , 'type': 'lens', 'id': LENS_ID__TOP_SERVICES   },
            {'name': 'panel_lens-avg-duration'    , 'type': 'lens', 'id': LENS_ID__AVG_DURATION   },
        ],
    }


def panel(panel_index: str, ref_name: str, x: int, y: int, w: int, h: int) -> dict:
    return {'version'         : '8.13.4',
            'type'            : 'lens',
            'gridData'        : {'x': x, 'y': y, 'w': w, 'h': h, 'i': panel_index},
            'panelIndex'      : panel_index,
            'embeddableConfig': {'enhancements': {}},
            'panelRefName'    : ref_name}


class Default__Dashboard__Generator(Type_Safe):

    @type_safe
    def build_ndjson(self, index        : str ,                                     # ES index name (also the data view title)
                            data_view_id : str ,                                     # Kibana data view UUID — baked into every reference
                            time_field   : str = 'timestamp'
                       ) -> bytes:
        # Layout: 2x2 grid, each panel 24w x 12h on a 48-column canvas (Kibana default)
        panels = [panel('p1', 'panel_lens-log-levels'     ,  0,  0, 24, 12),
                  panel('p2', 'panel_lens-volume-by-level', 24,  0, 24, 12),
                  panel('p3', 'panel_lens-top-services'   ,  0, 12, 24, 12),
                  panel('p4', 'panel_lens-avg-duration'   , 24, 12, 24, 12)]
        panels_json_string = json.dumps(panels)

        objects: List[dict] = [
            lens_log_levels     (data_view_id),
            lens_volume_by_level(data_view_id, time_field),
            lens_top_services   (data_view_id),
            lens_avg_duration   (data_view_id, time_field),
            dashboard           (panels_json_string),
        ]
        # ndjson: one JSON object per line, no trailing comma, no enclosing array
        return ('\n'.join(json.dumps(o) for o in objects) + '\n').encode('utf-8')

    def dashboard_id(self) -> str:                                                  # So callers can render it without importing the module-level constant
        return DASHBOARD_ID

    def dashboard_title(self) -> str:
        return DASHBOARD_TITLE
