# ═══════════════════════════════════════════════════════════════════════════════
# Playwright Service — Identifier Primitives
# ═══════════════════════════════════════════════════════════════════════════════

import re

from osbot_utils.type_safe.primitives.core.Safe_Str                          import Safe_Str
from osbot_utils.type_safe.primitives.core.enums.Enum__Safe_Str__Regex_Mode  import Enum__Safe_Str__Regex_Mode
from osbot_utils.type_safe.primitives.domains.identifiers.Safe_Id            import Safe_Id


class Session_Id(Safe_Id):                                                          # Browser session handle (auto-generates)
    pass                                                                            # Inherits Safe_Id auto-gen behaviour


class Sequence_Id(Safe_Id):                                                         # Sequence execution run (auto-generates)
    pass


class Step_Id(Safe_Str):                                                            # Per-step identifier within a sequence
    max_length      = 64                                                            # Caller may specify meaningful names
    regex           = re.compile(r'[^a-zA-Z0-9_\-.]')                               # Alphanumerics + _ - .
    regex_mode      = Enum__Safe_Str__Regex_Mode.REPLACE
    allow_empty     = True                                                          # Steps without explicit IDs use index


class Safe_Str__Trace_Id(Safe_Str):                                                 # Request-level correlation ID
    max_length      = 32                                                            # Short hex (8-16 chars) or W3C 32-hex
    regex           = re.compile(r'[^a-f0-9\-]')                                    # Lowercase hex + hyphens only
    regex_mode      = Enum__Safe_Str__Regex_Mode.REPLACE
    allow_empty     = True                                                          # Auto-generated by runner if empty
    trim_whitespace = True
