# ═══════════════════════════════════════════════════════════════════════════════
# SG/Compute Specs — Docker: Schema__Docker__Create__Request
# ═══════════════════════════════════════════════════════════════════════════════

from typing                                                                         import List

from osbot_utils.type_safe.Type_Safe                                                import Type_Safe
from osbot_utils.type_safe.primitives.domains.common.safe_str.Safe_Str__Text        import Safe_Str__Text

from sg_compute.platforms.ec2.primitives.Safe_Str__AMI__Id             import Safe_Str__AMI__Id
from sg_compute.primitives.Safe_Str__AWS__Region import Safe_Str__AWS__Region

from sg_compute_specs.docker.primitives.Safe_Str__IP__Address                       import Safe_Str__IP__Address
from sg_compute_specs.docker.primitives.Safe_Str__Docker__Stack__Name               import Safe_Str__Docker__Stack__Name


class Schema__Docker__Create__Request(Type_Safe):
    stack_name    : Safe_Str__Docker__Stack__Name
    region        : Safe_Str__AWS__Region
    instance_type : Safe_Str__Text           = 't3.medium'
    from_ami      : Safe_Str__AMI__Id
    caller_ip     : Safe_Str__IP__Address
    max_hours     : int                      = 1
    extra_ports   : List[int]
    registry      : str                      = ''            # ECR registry host; when set the host control plane sidecar is started
    api_key_name  : str                      = 'X-API-Key'
    api_key_ssm_path : str                      = ''            # generated by service if empty
    enable_shell  : bool                     = False         # when True, disables the shell command allowlist on the sidecar
