# ═══════════════════════════════════════════════════════════════════════════════
# Playwright Service — Safe_Str__Trace_Id primitive
# ═══════════════════════════════════════════════════════════════════════════════

import re

from osbot_utils.type_safe.primitives.core.Safe_Str                          import Safe_Str
from osbot_utils.type_safe.primitives.core.enums.Enum__Safe_Str__Regex_Mode  import Enum__Safe_Str__Regex_Mode


class Safe_Str__Trace_Id(Safe_Str):                                                 # Request-level correlation ID
    max_length      = 32                                                            # Short hex (8-16 chars) or W3C 32-hex
    regex           = re.compile(r'[^a-f0-9\-]')                                    # Lowercase hex + hyphens only
    regex_mode      = Enum__Safe_Str__Regex_Mode.REPLACE
    allow_empty     = True                                                          # Auto-generated by runner if empty
    trim_whitespace = True
