# ═══════════════════════════════════════════════════════════════════════════════
# SP CLI — CF__Events__Dashboard__Builder
# Builds the saved-objects ndjson for the "CloudFront Logs - Events Overview"
# dashboard.  Mirrors slice 1's CF__Inventory__Dashboard__Builder pattern —
# legacy `visualization` saved-object type (Vis Editor), NOT Lens.  Same
# migration-safety reasoning as slice 1 (the synthetic-data debrief flagged
# Lens migration footguns).
#
# Six panels, each sourced from the sg-cf-events-* data view (time field:
# timestamp):
#   1. Status code distribution over time   stacked vertical bar
#   2. Edge result type breakdown            donut
#   3. Top URIs                              horizontal bar
#   4. Geographic distribution               donut
#   5. Time-taken percentiles over time      line (p50/p95/p99)
#   6. Bot vs human ratio over time          stacked vertical bar
#
# Layout: 3x2 grid (3 rows of 2 panels), each panel 24w x 12h on Kibana's
# 48-column canvas.
#
# Field naming notes (slice 1 lesson: terms aggs need .keyword on string
# fields; numeric fields use the raw name):
#   - sc_status_class.keyword       (text + .keyword)
#   - x_edge_result_type.keyword    (text + .keyword)
#   - cs_uri_stem.keyword           (text + .keyword)
#   - c_country.keyword             (text + .keyword)
#   - bot_category.keyword          (text + .keyword)
#   - time_taken_ms                 (long, numeric — direct)
# ═══════════════════════════════════════════════════════════════════════════════

import json
from typing                                                                         import List

from osbot_utils.type_safe.Type_Safe                                                import Type_Safe
from osbot_utils.type_safe.type_safe_core.decorators.type_safe                      import type_safe

from sgraph_ai_service_playwright__cli.elastic.lets.cf.events.service.CF__Events__Dashboard__Ids import (
    DASHBOARD_ID, DASHBOARD_TITLE,
    VIS_ID__STATUS_OVER_TIME, VIS_ID__EDGE_RESULT, VIS_ID__TOP_URIS,
    VIS_ID__GEOGRAPHIC, VIS_ID__LATENCY_PERCENTILES, VIS_ID__BOT_VS_HUMAN,
)


DASHBOARD_DESCRIPTION = 'Auto-generated by `sp el lets cf events load`. Edit or replace via Kibana UI.'

DATA_VIEW_REF_NAME    = 'kibanaSavedObjectMeta.searchSourceJSON.index'


def search_source_json() -> str:
    return json.dumps({'query'        : {'language': 'kuery', 'query': ''},
                       'filter'       : []                                  ,
                       'indexRefName' : DATA_VIEW_REF_NAME                  })


def vis_object(vis_id: str, title: str, vis_state: dict, data_view_id: str) -> dict:
    return {
        'id'        : vis_id,
        'type'      : 'visualization',
        'attributes': {
            'title'                 : title,
            'visState'              : json.dumps(vis_state),
            'uiStateJSON'           : '{}',
            'description'           : '',
            'version'               : 1,
            'kibanaSavedObjectMeta' : {'searchSourceJSON': search_source_json()},
        },
        'references': [
            {'name': DATA_VIEW_REF_NAME, 'type': 'index-pattern', 'id': data_view_id},
        ],
    }


# ─── panel 1: status code distribution over time ─────────────────────────────
def vis_status_over_time(data_view_id: str, time_field: str = 'timestamp') -> dict:
    state = {
        'title' : 'Status code distribution over time',
        'type'  : 'histogram',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Request count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'stacked',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
            {'id': '3', 'enabled': True, 'type': 'terms', 'schema': 'group',
             'params': {'field': 'sc_status_class.keyword', 'size': 6,                # 5 named classes + OTHER
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__STATUS_OVER_TIME, 'Status code distribution over time', state, data_view_id)


# ─── panel 2: edge result type breakdown ─────────────────────────────────────
def vis_edge_result(data_view_id: str) -> dict:
    state = {
        'title' : 'Edge result type breakdown',
        'type'  : 'pie',
        'params': {
            'type'           : 'pie',
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'isDonut'        : True,
            'labels'         : {'show': False, 'values': True, 'last_level': True, 'truncate': 100},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'x_edge_result_type.keyword', 'size': 12,             # 9 known + a few defensive
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__EDGE_RESULT, 'Edge result type breakdown', state, data_view_id)


# ─── panel 3: top URIs ───────────────────────────────────────────────────────
def vis_top_uris(data_view_id: str) -> dict:
    state = {
        'title' : 'Top URIs by request count',
        'type'  : 'horizontal_bar',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'left', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 200}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'BottomAxis-1', 'type': 'value', 'position': 'bottom',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 75, 'filter': True, 'truncate': 100},
                                  'title': {'text': 'Request count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'normal',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : False,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': True},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'cs_uri_stem.keyword', 'size': 25,                     # Top 25 URIs
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__TOP_URIS, 'Top URIs by request count', state, data_view_id)


# ─── panel 4: geographic distribution ────────────────────────────────────────
def vis_geographic(data_view_id: str) -> dict:
    state = {
        'title' : 'Geographic distribution (by country)',
        'type'  : 'pie',
        'params': {
            'type'           : 'pie',
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'isDonut'        : True,
            'labels'         : {'show': False, 'values': True, 'last_level': True, 'truncate': 100},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'terms', 'schema': 'segment',
             'params': {'field': 'c_country.keyword', 'size': 25,                       # Top 25 countries
                        'order': 'desc', 'orderBy': '1', 'otherBucket': True, 'otherBucketLabel': 'Other',
                        'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__GEOGRAPHIC, 'Geographic distribution (by country)', state, data_view_id)


# ─── panel 5: time-taken percentiles over time ───────────────────────────────
def vis_latency_percentiles(data_view_id: str, time_field: str = 'timestamp') -> dict:
    state = {
        'title' : 'Time-taken percentiles over time (ms)',
        'type'  : 'line',
        'params': {
            'type'           : 'line',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'time_taken_ms'}}],
            'seriesParams'   : [{'show': True, 'type': 'line', 'mode': 'normal',
                                  'data': {'label': 'Percentiles', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'percentiles', 'schema': 'metric',
             'params': {'field': 'time_taken_ms', 'percents': [50, 95, 99]}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
        ],
    }
    return vis_object(VIS_ID__LATENCY_PERCENTILES, 'Time-taken percentiles over time (ms)', state, data_view_id)


# ─── panel 6: bot vs human ratio over time ───────────────────────────────────
def vis_bot_vs_human(data_view_id: str, time_field: str = 'timestamp') -> dict:
    state = {
        'title' : 'Bot vs human traffic over time',
        'type'  : 'histogram',
        'params': {
            'type'           : 'histogram',
            'grid'           : {'categoryLines': False},
            'categoryAxes'   : [{'id': 'CategoryAxis-1', 'type': 'category', 'position': 'bottom', 'show': True,
                                  'style': {}, 'scale': {'type': 'linear'},
                                  'labels': {'show': True, 'filter': True, 'truncate': 100}, 'title': {}}],
            'valueAxes'      : [{'id': 'ValueAxis-1', 'name': 'LeftAxis-1', 'type': 'value', 'position': 'left',
                                  'show': True, 'style': {},
                                  'scale': {'type': 'linear', 'mode': 'normal'},
                                  'labels': {'show': True, 'rotate': 0, 'filter': False, 'truncate': 100},
                                  'title': {'text': 'Request count'}}],
            'seriesParams'   : [{'show': True, 'type': 'histogram', 'mode': 'stacked',
                                  'data': {'label': 'Count', 'id': '1'},
                                  'valueAxis': 'ValueAxis-1',
                                  'drawLinesBetweenPoints': True, 'showCircles': True}],
            'addTooltip'     : True,
            'addLegend'      : True,
            'legendPosition' : 'right',
            'times'          : [],
            'addTimeMarker'  : False,
            'labels'         : {'show': False},
        },
        'aggs': [
            {'id': '1', 'enabled': True, 'type': 'count', 'schema': 'metric', 'params': {}},
            {'id': '2', 'enabled': True, 'type': 'date_histogram', 'schema': 'segment',
             'params': {'field': time_field, 'useNormalizedEsInterval': True,
                        'interval': 'auto', 'drop_partials': False,
                        'min_doc_count': 1, 'extended_bounds': {}}},
            {'id': '3', 'enabled': True, 'type': 'terms', 'schema': 'group',
             'params': {'field': 'bot_category.keyword', 'size': 4,                     # Four enum values
                        'order': 'desc', 'orderBy': '1', 'otherBucket': False, 'missingBucket': False}},
        ],
    }
    return vis_object(VIS_ID__BOT_VS_HUMAN, 'Bot vs human traffic over time', state, data_view_id)


# ─── dashboard wrapper ───────────────────────────────────────────────────────
def dashboard(panels_json_string: str) -> dict:
    return {
        'id'   : DASHBOARD_ID,
        'type' : 'dashboard',
        'attributes': {
            'title'                   : DASHBOARD_TITLE,
            'description'             : DASHBOARD_DESCRIPTION,
            'panelsJSON'              : panels_json_string,
            'optionsJSON'             : json.dumps({'useMargins': True, 'syncColors': False,
                                                     'syncCursor': True, 'syncTooltips': False,
                                                     'hidePanelTitles': False}),
            'version'                 : 1,
            'timeRestore'             : False,
            'kibanaSavedObjectMeta'   : {'searchSourceJSON': json.dumps({'query': {'language': 'kuery', 'query': ''},
                                                                          'filter': []})},
        },
        'references': [
            {'name': 'panel_p1', 'type': 'visualization', 'id': VIS_ID__STATUS_OVER_TIME      },
            {'name': 'panel_p2', 'type': 'visualization', 'id': VIS_ID__EDGE_RESULT           },
            {'name': 'panel_p3', 'type': 'visualization', 'id': VIS_ID__TOP_URIS              },
            {'name': 'panel_p4', 'type': 'visualization', 'id': VIS_ID__GEOGRAPHIC            },
            {'name': 'panel_p5', 'type': 'visualization', 'id': VIS_ID__LATENCY_PERCENTILES   },
            {'name': 'panel_p6', 'type': 'visualization', 'id': VIS_ID__BOT_VS_HUMAN          },
        ],
    }


def panel(panel_index: str, x: int, y: int, w: int, h: int) -> dict:
    return {'version'         : '8.13.4',
            'type'            : 'visualization',
            'gridData'        : {'x': x, 'y': y, 'w': w, 'h': h, 'i': panel_index},
            'panelIndex'      : panel_index,
            'embeddableConfig': {'enhancements': {}},
            'panelRefName'    : f'panel_{panel_index}'}


class CF__Events__Dashboard__Builder(Type_Safe):

    @type_safe
    def build_ndjson(self, data_view_id : str ,
                            time_field   : str = 'timestamp'
                       ) -> bytes:
        # Layout: 3x2 grid (3 rows, 2 panels each), 24w x 12h on a 48-column canvas
        panels = [panel('p1',  0,  0, 24, 12),
                  panel('p2', 24,  0, 24, 12),
                  panel('p3',  0, 12, 24, 12),
                  panel('p4', 24, 12, 24, 12),
                  panel('p5',  0, 24, 24, 12),
                  panel('p6', 24, 24, 24, 12)]
        panels_json_string = json.dumps(panels)

        objects: List[dict] = [
            vis_status_over_time   (data_view_id, time_field),
            vis_edge_result        (data_view_id),
            vis_top_uris           (data_view_id),
            vis_geographic         (data_view_id),
            vis_latency_percentiles(data_view_id, time_field),
            vis_bot_vs_human       (data_view_id, time_field),
            dashboard              (panels_json_string),
        ]
        return ('\n'.join(json.dumps(o) for o in objects) + '\n').encode('utf-8')

    def dashboard_id(self) -> str:
        return DASHBOARD_ID

    def dashboard_title(self) -> str:
        return DASHBOARD_TITLE
